### ISSUE TITLE
JoyStick cannot notrol husky

### ISSUE THREAD

**Issue by Karin-Sugi** [husky/husky#256]
Hi, as i mentioned in the title, my husky bacame unable to be cobtroled by joystick suddenly!

All lights (battery, comm...) are green, but husky never move. 
I sent command by ssh to both `/husky_velocity_controller/cmd_vel` and `/joy_teleop/cmd_vel`. Both of them worked(/joy_teleop/cmd_vel didn't worked at first but second time, fine). Also, i tried `rostopic echo /joy_teleop/cmd_vel` while using joy sticks, and it returns ONLY one data as like below.
```
linear:
        x: 0.0
        y: 0.0
        z: 0.0
angular:
        x: 0.0
        y: 0.0
        z: 0.0
```
I think the data from joy stick isn't sent to the ros topic, but it seems the USB of joy stick is recognized (I saw its name when I do lsusb).

How can i solve it?
I use ros-melodic and my husky is "HUSKY A200".

Thanks in advance,
Karin
