### ISSUE TITLE
How to set IP address of wired net work?

### ISSUE THREAD

**Issue by Karin-Sugi** [husky/husky#292]
Hi, as i mentioned, now I'd like to fix IP address in wired network because the address sometimes changes. I already know the way in wifi network following [this](https://www.clearpathrobotics.com/assets/guides/melodic/husky/HuskyNetwork.html) .

I tried to do that with netplan yaml file, but it doesn't look working...

Any solutions?

Thanks, in advance
Karin

**Comment by civerachb-cpr** [comment]
What's likely happening is that your Husky is being connected to a wired DHCP source, and the assigned address is rotating.

The best solution would probably be to look up the Husky's wired MAC address and modify your DHCP server to provide a static address allocation for that MAC.  Most consumer routers have an option to do this somewhere.  If you don't have access to the router's configuration (e.g. because it's a university or company owned router) you may need to go through your IT administrator to request this.  Alternatively, your IT administrator may also be able to assign you a static address outside the normal DHCP range.  In this case, you can modify your netplan file to simply use the fixed address:

```
bridges:
  br0:
    dhcp4: no                   # CHANGE: yes -> no
    dhcp6: no
    interfaces: [bridge_eth, bridge_en]
    addresses:
      - 192.168.131.1/24
      - 10.27.204.101/16        # ADD: this line, with your desired IP address and the netmask size
```

Because DHCP allocations are outside our direct control we cannot provide an exact solution. But hopefully you can take this information to your IT administrator and they can work with you to solve the problem.
